image: node:latest

cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  script:
    - yarn
    - yarn data
    - yarn build
    - cp -r dist/* public/
  artifacts:
    paths:
      - public
