image: node:latest

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - yarn
    - yarn data

deploy:
  stage: deploy
  script:
    - yarn build
    - mkdir .public
    - cp -r dist/* .public/
  artifacts:
    paths:
      - .public
  environment: production
